version: "3"
services:
  awsmonogodbserver:
    image: mongo:latest
    container_name: "awsmonogodbserver"
    ports:
      - 27017:27017

  sb-jwt-mongo-app:
    image: sbjwtmongo
    container_name: "sb-jwt-mongo-app"
    ports:
      - 9090:8080
    links:
      - awsmonogodbserver
